version: '3.8'

services:
  nodejs:
    container_name: nodejs
    tty: true
    image: 'node:latest'
    restart: always
    ports:
      - '3000:3000'
    volumes:
        - ./:/var/www/html/app/
    working_dir: /var/www/html/app/
    #command: bash -c "npm install && npm start"
